version: '3.1'

services:
  redis:
    image: redis:alpine
    ports: ["6379"]

  user-service:
    image: webdevtoolsandtech/user-service
    ports: ["80"]
    environment:
      REDIS_ADDRESS: 'redis:6379'

  currency-calculator:
    image: currcalc
    build:
      context: CurrencyCalculator
      dockerfile: .Dockerfile
    ports: ["80"]

  currency-frontend:
    image: webdevtoolsandtech/currency-frontend
    ports: ["80"]

  currency-backend:
    image: webdevtoolsandtech/currency-backend
    ports: ["80"]
    environment:
      REDIS_ADDRESS: 'redis:6379'
      SESSION_SECRET: 'lalala'
      USER_SERVICE_ADDRESS: 'user-service'
      FRONTEND_ADDRESS: 'currency-frontend'
      CALCULATOR_ADDRESS: 'currency-calculator'
